@ownerId = 550e8400-e29b-41d4-a716-446655440000

### 1. Restaurant toevoegen
POST http://localhost:8080/api/restaurant/addRestaurant
Content-Type: application/json

{
  "ownerId": "{{ownerId}}",
  "addressId": "b12d5c1a-3d1f-4b8f-9f9a-11a2b3c4d5e6",
  "restaurantType": "BUFFET",
  "name": "La Bella Vita",
  "email": "info@labellavita.com",
  "logo": "https://example.com/logo.png",
  "dishes": []
}

> {% client.global.set("restaurantId", response.body.id); %}


### 2. Dish toevoegen (restaurantId automatisch ingevuld)
POST http://localhost:8080/api/restaurant/addDish
Content-Type: application/json

{
  "RestaurantId": "{{restaurantId}}",
  "name": "Spaghetti Bolognese",
  "description": "Classic Italian pasta with meat sauce",
  "price": 12.50
}

> {% client.global.set("dishId", response.body.id); %}

### 2.1 tweede Dish toevoegen (restaurantId automatisch ingevuld)
POST http://localhost:8080/api/restaurant/addDish
Content-Type: application/json

{
  "RestaurantId": "{{restaurantId}}",
  "name": "frietjes",
  "description": "met stoofvlees",
  "price": 20
}

> {% client.global.set("dishId2", response.body.id); %}


### 3. Dish status veranderen (dishId automatisch gebruikt)
PUT http://localhost:8080/api/restaurant/changeStateDish/{{dishId}}
Content-Type: application/json

"PUBLISHED"


### 4. Restaurant openen of sluiten
PUT http://localhost:8080/api/restaurant/{{restaurantId}}/changeOpenState?ownerId={{ownerId}}


### 5. Schedule een dish change (bv. naar NOT_PUBLISHED over 2 minuten)
POST http://localhost:8080/api/restaurant/scheduleDishChange
Content-Type: application/json

{
  "dishId": "{{dishId}}",
  "scheduledTime": "2025-09-30T15:42:01.222",
  "targetState": "NOT_PUBLISHED",
  "targetName": "spaghetti Bolognese",
  "targetDescription": "Verse pasta met huisgemaakte saus",
  "targetPrice": 15
}

### 5.1 Schedule een tweede dish change (bv. naar NOT_PUBLISHED over 2 minuten)
POST http://localhost:8080/api/restaurant/scheduleDishChange
Content-Type: application/json

{
  "dishId": "{{dishId2}}",
  "scheduledTime": "2025-09-30T15:42:01.222",
  "targetState": "NOT_PUBLISHED",
  "targetName": "frietjes",
  "targetDescription": "zonder stoofvlees",
  "targetPrice": 15
}


### 6. Voer alle geschedulde dish changes uit

POST http://localhost:8080/api/restaurant/applyAllScheduledChangesForRestaurant?ownerId={{ownerId}}&restaurantId={{restaurantId}}
Content-Type: application/json

### 7. Haal overzicht op van alle gerechten en geplande weizegingen van een restaurant als owner

GET http://localhost:8080/api/restaurant/{{restaurantId}}/changesOverview?ownerId={{ownerId}}
Accept: application/json

