spring.application.name=Restaurant Service
# Toon SQL queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.datasource.url=jdbc:postgresql://localhost:5443/postgres?currentSchema=restaurant
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.sql=debug
logging.level.web=debug

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

