spring.application.name=Restaurant Service
# Toon SQL queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.sql.init.data-locations=classpath*:sql/data.sql

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.datasource.url=jdbc:postgresql://localhost:5443/postgres?currentSchema=restaurant
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.sql=debug
logging.level.web=debug

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

#keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/keepdishesgoing
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/keepdishesgoing/protocol/openid-connect/certs
server.port=8080


#Values
rabbit.order.exchange=order-exchange
rabbit.restaurant.response.exchange=restaurant-response-exchange
rabbit.delivery.exchange=delivery-exchange
rabbit.restaurant.order.queue=restaurant-order-queue

restaurant.max.published_dishes=10
restaurant.cheap.category=10
restaurant.normal.category=30
restaurant.expensive.category=60

rabbit.order.routing.key=order.place.*
rabbit.order.deny.routing.key=order.deny.
rabbit.order.accept.routing.key=order.accept.
rabbit.order.ready.routing.key=order.ready.